FROM registry.access.redhat.com/ubi9/python-311:1-62.1714671026
WORKDIR /sentiment
COPY requirements.txt .
COPY promptfooconfig.yaml .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /sentiment/requirements.txt
COPY review-responder.py .
EXPOSE 8501
ENTRYPOINT [ "streamlit", "run", "review-responder.py" ]
